---
title: "N3_Depth_Profiles"
author: "Nicholas Baetge"
date: "12/28/2021"
output: github_document
---

# Intro

Here, we plot the profiles from the  NAAMES stations N3 S3, 3.5, 4, and 6.

```{r load libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(hms)
library(zoo) 
library(oce)  
library(ggpubr)
library(patchwork)
```


# Import Data

These casts have been excluded from further analysis (see Float and Ship T-S analysis): 


```{r}
bf <- read_rds("~/GITHUB/naames_multiday/Input/bottle_data.rds") %>% 
  filter(Cruise == "AT38", Station %in% c(3, 3.5, 4, 6), z > 0, z <= 200, !plot_date %in% c("Sep 8 03:08",  "Sep 8 15:30", "Sep 11 03:07", "Sep 14 15:33", "Sep 15 03:04", "Sep 15 15:20", "Sep 16 03:04", "Sep 16 04:50", "Sep 16 07:26")) %>% 
  mutate(name = ifelse(Cruise == "AT34", "NAAMES 2", "NAAMES 3"), 
         plot_name = paste(name, "Station", Station),
         plot_sep = ifelse(Station == "6", "Subpolar", "Subtropical")) 
  
ctd <- read_rds("~/GITHUB/naames_multiday/Input/ctd_data.rds") %>% 
   filter(Cruise == "AT38", Station %in% c(3, 3.5, 4, 6), z > 0, z <= 200, !plot_date %in% c("Sep 8 03:08", "Sep 8 15:30", "Sep 11 03:07", "Sep 14 15:33", "Sep 15 03:04", "Sep 15 15:20", "Sep 16 03:04", "Sep 16 04:50", "Sep 16 07:26"))  %>% 
  mutate(name = ifelse(Cruise == "AT34", "NAAMES 2", "NAAMES 3"), 
         plot_name = paste(name, "Station", Station),
         plot_sep = ifelse(Station == "6", "Subpolar", "Subtropical"))

npp <- read_rds("~/GITHUB/naames_multiday/Input/npp_data.rds") %>% 
   filter(Cruise == "AT38", Station %in% c(3, 3.5, 4, 6), z > 0, z <= 200, !plot_date %in% c("Sep 8 03:08",  "Sep 8 15:30", "Sep 11 03:07", "Sep 14 15:33", "Sep 15 03:04", "Sep 15 15:20", "Sep 16 03:04", "Sep 16 04:50", "Sep 16 07:26"))  %>% 
  mutate(name = ifelse(Cruise == "AT34", "NAAMES 2", "NAAMES 3"), 
         plot_name = paste(name, "Station", Station),
         plot_sep = ifelse(Station == "6", "Subpolar", "Subtropical"))

phyto <- read_rds("~/GITHUB/naames_multiday/Input/phyto_data.rds") %>% 
   filter(Cruise == "AT38", station %in% c("S3", "S3.5", "S4", "S6"), depth > 0, depth <= 200, !plot_date %in% c("Sep 8 03:08",  "Sep 8 15:30", "Sep 11 03:07", "Sep 14 15:33", "Sep 15 03:04", "Sep 15 15:20", "Sep 16 03:04", "Sep 16 04:50", "Sep 16 07:26")) %>% 
  mutate(station = gsub("S", "", station),
         station = as.character(station),
         name = ifelse(Cruise == "AT34", "NAAMES 2", "NAAMES 3"), 
         plot_name = paste(name, "Station", station),
         plot_sep = ifelse(station == "S6", "Subpolar", "Subtropical"))

custom.shapes <- c("NAAMES 2 Station 4" = 21, "NAAMES 3 Station 3" = 22, "NAAMES 3 Station 3.5" = 23, "NAAMES 3 Station 4" = 24, "NAAMES 3 Station 6" = 25) 


```


```{r}
n2_bf <- read_rds("~/GITHUB/naames_multiday/Input/bottle_data.rds") %>% 
  filter(Cruise == "AT34", Station == 4, !plot_date %in% c("May 24 02:30", "May 27 06:07"), z > 0, z <= 200) 

n2_phyto <- read_rds("~/GITHUB/naames_multiday/Input/phyto_data.rds") %>% 
   filter(Cruise == "AT34", station == "S4", !plot_date %in% c("May 24 02:30", "May 27 06:07"), depth > 0, depth <= 200) 
  
n2_ctd <- read_rds("~/GITHUB/naames_multiday/Input/ctd_data.rds") %>% 
   filter(Cruise == "AT34", Station == 4, !plot_date %in% c("May 24 02:30", "May 27 06:07"), z > 0, z <= 200) 


n2_npp <- read_rds("~/GITHUB/naames_multiday/Input/npp_data.rds") %>% 
   filter(Cruise == "AT34", Station == 4, !plot_date %in% c("May 24 02:30", "May 27 06:07"), z > 0, z <= 200) 
```


```{r}
# bf %>% filter(z <= 57) %>% select(leu_incorp) %>% summary
```


```{r}
# npp %>% filter(z <= 57) %>% select(npp) %>% mutate(sd = sd(npp, na.rm = T)) %>% 
#   select(sd) %>% unique()
```


```{r}
 # n2_npp %>% filter(z <= 77) %>% select(npp) %>% summary
```



```{r}
# n2_npp %>% filter(z <= 77) %>% select(npp) %>% mutate(sd = sd(npp, na.rm = T)) %>% 
#   select(sd) %>% unique()
```

```{r}
# npp %>% filter(z >= 57) %>% select(npp) %>% summary
```


```{r}
# npp %>% filter(z >= 57) %>% select(npp) %>% mutate(sd = sd(npp, na.rm = T)) %>% 
#   select(sd) %>% unique()
```


```{r}
 # n2_bf %>% filter(z >= 77, Date == "2016-05-26") %>% select(leu_incorp) %>% summary
```



```{r}
# n2_bf %>% filter(z >= 77, Date == "2016-05-26") %>% select(leu_incorp) %>%  mutate(sd = sd(leu_incorp, na.rm = T)) %>%
#   select(sd) %>% unique()
```



## Plot Profiles 

### Chl

```{r chl plot, echo = FALSE, warning = FALSE, message = FALSE}

chl.plot <-  bf %>% 
  drop_na(chl) %>% 
  # µg / L = mg / m3
  group_by(Station, z) %>% 
  mutate(ave = ifelse(Station == 6, mean(chl, na.rm = T), chl),
         sd = ifelse(Station == 6, sd(chl, na.rm = T), NA)) %>% 
  ungroup() %>% 
  select(plot_name, z, ave, sd) %>% 
  distinct() %>% 
  ggplot(aes(x = z, y = ave, color = plot_name, fill = plot_name)) +
  geom_vline(xintercept = 57, color = "red") +
  geom_errorbar(aes(ymin = ave - sd, ymax = ave + sd), color = "black", width = 5) +
  geom_line(size = 0.7) +
  geom_point(shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "Depth, m", y = expression(paste("Chl ", italic("a"), ", ug L"^"-1")), colour = "", fill = "Station") +
  expand_limits(x = 200) +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d(begin = 0.65) +
  scale_color_viridis_d(begin = 0.65) +
  guides(color = F, fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.1),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```

### Phyto Cells

```{r phyto plot, echo = FALSE, warning = FALSE, message = FALSE}
phyto.plot <-  phyto %>% 
  # mutate(phyto = phyto * 10^3) %>% 
  select(station, plot_date, plot_name, depth, phyto) %>% 
  group_by(station, depth) %>% 
  mutate(ave = ifelse(station == 6, mean(phyto, na.rm = T), phyto),
         sd = ifelse(station == 6, sd(phyto, na.rm = T), NA)) %>% 
  ungroup() %>% 
  select(plot_name, depth, ave, sd) %>% 
  distinct() %>% 
  ggplot(aes(x = depth, y = ave, color = plot_name, fill = plot_name)) +
  geom_vline(xintercept = 57, color = "red") +
  geom_errorbar(aes(ymin = ave - sd, ymax = ave + sd), color = "black", width = 5) +
  geom_line(size = 0.7) +
  geom_point(shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "", y = expression(paste("Phytoplankton, cells L"^"-1")), color = "", fill = "Date") +
  expand_limits(x = 200) +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(color = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.15),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))
```

### NPP

```{r npp plot, echo = FALSE, warning = FALSE, message = FALSE}
npp.plot <-  npp %>% 
  # mutate(npp = npp/10^3) %>% 
   group_by(Station, z) %>% 
  mutate(ave = ifelse(Station == 6, mean(npp, na.rm = T), npp),
         sd = ifelse(Station == 6, sd(npp, na.rm = T), NA)) %>% 
  ungroup() %>% 
  select(plot_name, z, ave, sd) %>% 
  distinct() %>% 
  ggplot(aes(x = z, y = ave, color = plot_name, fill = plot_name)) +
  geom_vline(xintercept = 57, color = "red") +
  geom_ribbon(aes(ymin = ave - sd, ymax = ave + sd), alpha = 0.3, color = "black", linetype = 2, width = 5) +
  geom_line(size = 1) +
  labs(x = "", y = expression(paste("Modeled NPP, µmol C L"^-1, " d"^-1)), colour = "Date") +
  expand_limits(x = 200) +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(fill = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.1),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```

### N

```{r n plot, echo = FALSE, warning = FALSE, message = FALSE}
n.plot <-  bf %>% 
  drop_na(n) %>% 
  
  group_by(Station, z) %>% 
  mutate(ave = ifelse(Station == 6, mean(n, na.rm = T), n),
         sd = ifelse(Station == 6, sd(n, na.rm = T), NA)) %>% 
  ungroup() %>% 
  select(plot_name, z, ave, sd) %>% 
  distinct() %>% 
  ggplot(aes(x = z, y = ave, color = plot_name, fill = plot_name)) +
  geom_vline(xintercept = 57, color = "red") +
  geom_errorbar(aes(ymin = ave - sd, ymax = ave + sd), color = "black", width = 5) +
  geom_line(size = 0.7) +
  geom_point(shape = 21, size = 6,  color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "Depth, m", y = expression(paste("N + N, µmol N L"^"-1"))) +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(colour = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.85),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```


### DOC

```{r doc plot, echo = FALSE, warning = FALSE, message = FALSE}
doc.plot <- bf %>% 
  drop_na(doc) %>% 
  
   group_by(Station, z) %>% 
  mutate(ave = ifelse(Station == 6, mean(doc, na.rm = T), doc),
         sd = ifelse(Station == 6, sd(doc, na.rm = T), NA)) %>% 
  ungroup() %>% 
  select(plot_name, z, ave, sd) %>% 
  distinct() %>% 
  ggplot(aes(x = z, y = ave, color = plot_name, fill = plot_name)) +
  geom_vline(xintercept = 57, color = "red") +
  geom_errorbar(aes(ymin = ave - sd, ymax = ave + sd), color = "black", width = 5) +
  
  geom_line(size = 0.7) +
  geom_point( shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "", y = expression(paste("DOC, µmol C L"^"-1")), colour = "", fill = "Date") +
  scale_x_reverse() +
  coord_flip() +
  # scale_y_continuous(limits = c(50, 60)) +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides( color = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.15),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```
### AOU

```{r aou plot, echo = FALSE, warning = FALSE, message = FALSE}
aou.plot <-  ctd %>% 
  drop_na(aou) %>% 
  
   group_by(Station, z) %>% 
  mutate(ave = mean(aou, na.rm = T),
         sd = sd(aou, na.rm = T), NA) %>% 
  ungroup() %>% 
  select(plot_name, z, ave, sd) %>% 
  distinct() %>% 
  ggplot(aes(x = z, y = ave, color = plot_name, fill = plot_name)) +
  geom_vline(xintercept = 57, color = "red") +
   geom_ribbon(aes(ymin = ave - sd, ymax = ave + sd), alpha = 0.3, color = "black", linetype = 2, width = 5) +
  geom_line(size = 0.7) +
  
  labs(x = "", y = expression(paste("AOU, µmol O"[2]," L"^"-1")), colour = "Date", fill = "") +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(fill = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.85),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```

### BactA

```{r bactC plot, echo = FALSE, warning = FALSE, message = FALSE}
ba.plot <-  bf %>% 
  drop_na(ba) %>% 
  filter(!plot_date %in% c("Sep 10 15:30"))  %>%

  
   group_by(Station, z) %>% 
  mutate(ave = ifelse(Station == 6, mean(ba, na.rm = T), ba),
         sd = ifelse(Station == 6, sd(ba, na.rm = T), NA)) %>% 
  ungroup() %>% 
  select(plot_name, z, ave, sd) %>% 
  distinct() %>% 
  ggplot(aes(x = z, y = ave, color = plot_name, fill = plot_name)) +
  geom_vline(xintercept = 57, color = "red") +
  geom_errorbar(aes(ymin = ave - sd, ymax = ave + sd), color = "black", width = 5) +
  
  geom_line(size = 0.7) +
  geom_point(shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "Depth, m", y = expression(paste("Bacterioplankton, cells L"^"-1")), colour = "", linetype = "Eddy Location", shape = "Eddy Location", fill = "Date") +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(colour = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.15),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```

### Leu

```{r bp plot, echo = FALSE, warning = FALSE, message = FALSE}
leu.plot <-  bf %>% 
  drop_na(bp) %>% 
  group_by(Station, z) %>% 
  mutate(ave = ifelse(Station == 6, mean(bp, na.rm = T), bp),
         sd = ifelse(Station == 6, sd(bp, na.rm = T), NA)) %>% 
  ungroup() %>% 
  select(plot_name, z, ave, sd) %>% 
  distinct() %>% 
  ggplot(aes(x = z, y = ave, color = plot_name, fill = plot_name)) +
  geom_vline(xintercept = 57, color = "red") +
  geom_errorbar(aes(ymin = ave - sd, ymax = ave + sd), color = "black", width = 5) +
  geom_line(size = 0.7) +
  geom_point(shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "", y = expression(paste("BP, nmol C L"^"-1","d"^-1)), colour = "", fill = "Date") +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(color = F, linetype = F, shape = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.15),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```

## Combine Plots

```{r combine plots, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 20, fig.width = 23}

patchwork <-  n.plot + (chl.plot ) + (phyto.plot ) + (npp.plot  ) + (aou.plot)  + (ba.plot + theme(legend.background = element_rect(size = 0.2, linetype = "solid", color = "black", fill = "transparent"), legend.box.background = element_rect(fill = 'transparent'))) + (leu.plot ) + (doc.plot) 

patchwork +  
  # plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(size = 22)) 

```
