---
title: "N3_Subtropical_Depth_Profiles"
author: "Nicholas Baetge"
date: "12/28/2021"
output: github_document
---

# Intro

Here, we plot the profiles from the  NAAMES station, N3S3 .

```{r load libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(hms)
library(zoo) 
library(oce)  
library(ggpubr)
library(patchwork)
```


# Import Data

These casts have been excluded from further analysis (see Float and Ship T-S analysis): 


```{r}
bf <- read_rds("~/GITHUB/naames_multiday/Input/bottle_data.rds") %>% 
  filter(Cruise == "AT38", Station %in% c(3, 3.5, 4), z <= 200, !plot_date %in% c("Sep 8 03:08",  "Sep 8 15:30", "Sep 11 03:07")) %>% 
  mutate(name = ifelse(Cruise == "AT34", "NAAMES 2", "NAAMES 3"), 
         plot_name = paste(name, "Station", Station),
         plot_sep = ifelse(Station == "6", "Subpolar", "Subtropical"))
  
ctd <- read_rds("~/GITHUB/naames_multiday/Input/ctd_data.rds") %>% 
   filter(Cruise == "AT38", Station %in% c(3, 3.5, 4), z <= 200, !plot_date %in% c("Sep 8 03:08", "Sep 8 15:30", "Sep 11 03:07"))  %>% 
  mutate(name = ifelse(Cruise == "AT34", "NAAMES 2", "NAAMES 3"), 
         plot_name = paste(name, "Station", Station),
         plot_sep = ifelse(Station == "6", "Subpolar", "Subtropical"))

npp <- read_rds("~/GITHUB/naames_multiday/Input/npp_data.rds") %>% 
   filter(Cruise == "AT38", Station %in% c(3, 3.5, 4), z <= 200)  %>% 
  mutate(name = ifelse(Cruise == "AT34", "NAAMES 2", "NAAMES 3"), 
         plot_name = paste(name, "Station", Station),
         plot_sep = ifelse(Station == "6", "Subpolar", "Subtropical"))

phyto <- read_rds("~/GITHUB/naames_multiday/Input/phyto_data.rds") %>% 
   filter(Cruise == "AT38", station %in% c("S3", "S3.5", "S4"), depth <= 200) %>% 
  mutate(name = ifelse(Cruise == "AT34", "NAAMES 2", "NAAMES 3"), 
         plot_name = paste(name, "Station", station),
         plot_sep = ifelse(station == "S6", "Subpolar", "Subtropical"))

```


## Plot Profiles 

### Chl

```{r chl plot, echo = FALSE, warning = FALSE, message = FALSE}

chl.plot <-  bf %>% 
  drop_na(chl) %>% 
  # µg / L = mg / m3
  ggplot(aes(x = z, y = chl, color = plot_name, fill = plot_name, group = interaction(datetime, CampCN))) +
  geom_line(size = 0.7) +
  geom_point(shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "Depth, m", y = expression(paste("Chl ", italic("a"), ", ug L"^"-1")), colour = "", fill = "Station") +
  expand_limits(x = 200) +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(color = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.1),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```

### Phyto Cells

```{r phyto plot, echo = FALSE, warning = FALSE, message = FALSE}
phyto.plot <-  phyto %>% 
  # mutate(phyto = phyto * 10^3) %>% 
  select(plot_date, plot_name, depth, phyto) %>% 
  ggplot(aes(x = depth, y = phyto, group = interaction(plot_date))) +
  # geom_errorbar(aes(x = z, ymin = ave_phyto - sd_phyto, ymax = ave_phyto + sd_phyto, color = plot_date)) +
  geom_line(aes(colour = plot_name), size = 0.7) +
  geom_point(aes(fill = plot_name), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "", y = expression(paste("Phytoplankton, cells L"^"-1")), color = "", fill = "Date") +
  expand_limits(x = 200) +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(colour = F, shape = F, linetype = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.15),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))
```

### NPP

```{r npp plot, echo = FALSE, warning = FALSE, message = FALSE}
npp.plot <-  npp %>% 
  # mutate(npp = npp/10^3) %>% 
  ggplot(aes(x = z, y = npp, group = plot_date)) +
  geom_line(aes(color = plot_name), size = 2) +
  labs(x = "", y = expression(paste("Modeled NPP, µmol C L"^-1, " d"^-1)), colour = "Date") +
  expand_limits(x = 200) +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(fill = F, shape = F, linetype = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.1),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```

### N

```{r n plot, echo = FALSE, warning = FALSE, message = FALSE}
n.plot <-  bf %>% 
  drop_na(n) %>% 
  ggplot(aes(x = z, y = n, group = interaction(plot_date, CampCN))) +
  geom_errorbar(aes(x = z, ymin = n - sd_n, ymax = n + sd_n), width = 5) +
  geom_line(aes(color = plot_name), size = 0.7) +
  geom_point(aes(fill = plot_name), shape = 21, size = 6,  color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "Depth, m", y = expression(paste("N + N, µmol N L"^"-1")), colour = "", fill = "Date") +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(colour = F, shape = F, linetype = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.85),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```


### DOC

```{r doc plot, echo = FALSE, warning = FALSE, message = FALSE}
doc.plot <- bf %>% 
  drop_na(doc) %>% 
  ggplot(aes(x = z, y = doc, group = interaction(plot_date, CampCN))) +
  geom_errorbar(aes(x = z, ymin = doc - sd_doc, ymax = doc + sd_doc, color = plot_name), width = 5) +
  geom_line(aes(color = plot_name), size = 0.7) +
  geom_point(aes(fill = plot_name), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "", y = expression(paste("DOC, µmol C L"^"-1")), colour = "", fill = "Date") +
  scale_x_reverse() +
  coord_flip() +
  # scale_y_continuous(limits = c(50, 60)) +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides( color = F, linetype = F, shape = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.15),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```
### AOU

```{r aou plot, echo = FALSE, warning = FALSE, message = FALSE}
aou.plot <-  ctd %>% 
  drop_na(aou) %>% 
  ggplot(aes(x = z, y = aou, group = plot_date)) +
  # geom_ribbon(aes(ymin = aou - sd_aou, ymax = aou + sd_aou, fill = plot_date), alpha = 0.5) +
  geom_line(aes(color = plot_name), size = 0.7) +
  labs(x = "", y = expression(paste("AOU, µmol O"[2]," L"^"-1")), colour = "Date", fill = "") +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(fill = F, shape = F, linetype = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.85),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```

### BactA

```{r bactC plot, echo = FALSE, warning = FALSE, message = FALSE}
ba.plot <-  bf %>% 
  drop_na(ba) %>% 
  filter(!plot_date %in% c("Sep 10 15:30"))  %>%
  ggplot(aes(x = z, y = ba, group = interaction(plot_date, CampCN))) +
  geom_errorbar(aes(x = z, ymin = ba - sd_ba, ymax = ba + sd_ba, color = plot_name), width = 5) +
  geom_line(aes(color = plot_name), size = 0.7) +
  geom_point(aes(fill = plot_name), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "Depth, m", y = expression(paste("Bacterioplankton, cells L"^"-1")), colour = "", linetype = "Eddy Location", shape = "Eddy Location", fill = "Date") +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(colour = F, shape = F, linetype = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.15),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```

### Leu

```{r bp plot, echo = FALSE, warning = FALSE, message = FALSE}
leu.plot <-  bf %>% 
  drop_na(leu_incorp) %>% 
  ggplot(aes(x = z, y = leu_incorp)) +
  geom_errorbar(aes(x = z, ymin = leu_incorp - sd_leu_incorp, ymax = leu_incorp + sd_leu_incorp, color = plot_name), width = 5) +
  geom_line(aes(color = plot_name), size = 0.7) +
  geom_point(aes(fill = plot_name), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = "", y = expression(paste("BP, pmol", " "^3,"H-Leu L"^"-1","h"^-1)), colour = "", fill = "Date") +
  scale_x_reverse() +
  coord_flip() +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  guides(color = F, linetype = F, shape = F) +
  theme_linedraw(base_size = 20) +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank(),
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.15),
        legend.text = element_text(size = 12),
        legend.background = element_rect(size = 0.2, linetype = "solid", color = "black"),
        legend.spacing.y = unit(0, "pt"))

```

## Combine Plots

```{r combine plots, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 20, fig.width = 23}

patchwork <-  n.plot + (chl.plot ) + (phyto.plot ) + (npp.plot  ) + (aou.plot)  + (ba.plot + theme(legend.background = element_rect(size = 0.2, linetype = "solid", color = "black", fill = "transparent"), legend.box.background = element_rect(fill = 'transparent'))) + (leu.plot ) + (doc.plot) 

patchwork +  
  # plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(size = 22)) 

```
