---
title: "ODV Plots"
author: "Nicholas Baetge"
date: "8/6/2020"
output: github_document
---
# Intro

Here, ODV-style section plots are made from data. Data are first transformed to represent z-scores (i.e. plots display anomalies for each depth)

```{r message = F, warning = F}
library(tidyverse) 
library(rmarkdown)
library(knitr)
library(readxl)
library(data.table) 
library(scales)
library(zoo)
library(oce)
library(patchwork)
library(lubridate)
#rmarkdown tables
library(stargazer)
library(pander)
#stat tests
library(lmtest)
library(lmodel2)
library(rstatix)
library(ggpubr)
#for odv type plots
library(reshape2)
library(MBA)
library(mgcv)

```

```{r}
custom_theme <- function() {
  theme_test(base_size = 30) %+replace%
    theme(legend.position = "right",
          legend.spacing.x = unit(0.5,"cm"),
          legend.title = element_text(size = 14),
          legend.text = element_text(size = 14),
          legend.background = element_rect(fill = "transparent",colour = NA),
          legend.key = element_rect(fill = "transparent",colour = NA),
          panel.background = element_rect(fill = "transparent",colour = NA),
          plot.background = element_rect(fill = "transparent",colour = NA)) 
}

custom.colors <- c("AT39" = "#377EB8", "AT34" = "#4DAF4A", "AT38" = "#E41A1C", "AT32" = "#FF7F00", "Temperate" = "#A6CEE3", "Subpolar" = "#377EB8", "Subtropical" = "#FB9A99", "GS/Sargasso" = "#E41A1C", "Early Spring" = "#377EB8", "Late Spring" = "#4DAF4A","Early Autumn" = "#E41A1C", "Late Autumn" = "#FF7F00")

levels = c("GS/Sargasso", "Subtropical", "Temperate", "Subpolar",  "AT39-6", "AT34", "AT38", "AT32", "Early Spring", "Late Spring","Early Autumn",  "Late Autumn")

odv.colors <- c("#feb483", "#d31f2a", "#ffc000", "#27ab19", "#0db5e6", "#7139fe", "#d16cfa")
```


# Import Data

```{r}
data <- read_rds("~/GITHUB/naames_multiday/Output/processed_data.rds") %>% 
  rename(lat = Latitude)

ctd <- read_rds("~/GITHUB/naames_multiday/Input/ctd/deriv_naames_ctd.rds") %>% 
  rename(lat = "Latitude [degrees_north]",
         z = bin_depth) %>% 
  mutate(bin = round(lat, 1))


#units for npp are mg C / d, we'll convert to µmol C / d
npp <- read_rds("~/GITHUB/naames_multiday/Input/Z_resolved_model_NPP.rds") %>% 
  rename(z = depth,
         npp = NPP) %>% 
  mutate(npp = round((npp * 10^3)/12)) %>% 
  left_join(., data %>% 
              select(Cruise, Station, Date, lat) %>% 
              distinct() %>% 
              group_by(Cruise, Station, Date) %>% 
              mutate(mean_lat = mean(lat)) %>% 
              ungroup() %>% 
              select(Cruise, Station, Date, mean_lat) %>% 
              distinct() %>% 
              rename(lat = mean_lat)) 


#markers for multiday stations
s4_ctd_mark <- ctd %>% 
  filter(between(z, 0, 300)) %>% 
  filter(Cruise == "AT34", Station == 4) %>% 
  select(lat, z) %>% 
  distinct()

s6_ctd_mark <- ctd %>% 
  filter(between(z, 0, 300)) %>% 
  filter(Cruise == "AT38", Station == 6) %>% 
  select(lat, z) %>% 
  distinct()

s4_data_mark <- data %>% 
  filter(between(z, 0, 300)) %>% 
  filter(Cruise == "AT34", Station == 4) %>% 
  distinct()

s6_data_mark <- data %>% 
  filter(between(z, 0, 300)) %>% 
  filter(Cruise == "AT38", Station == 6) %>% 
  distinct()
```

# Plot ODV-style composites

## BeamT

```{r}

subset <- ctd %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, beamT_perc) %>% 
  group_by(z) %>% 
  mutate(mean = mean(beamT_perc),
         sd = sd(beamT_perc),
         zscore = (beamT_perc - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z > 0)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z >= 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

beamt.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
  geom_raster(aes(fill = zscore)) +
  geom_vline(aes(xintercept = 47.25), linetype = 2, size = 2) +
  geom_vline(aes(xintercept = 47.75), linetype = 2, size = 2) +
  geom_point(data = subset, aes(x = lat, y = z), colour = "White", size = 0.4, shape = 3, alpha = 0.1) +
  # geom_point(data = s4_ctd_mark, aes(x = lat, y = z), colour = "Black", size = 0.4, shape = 3, alpha = 0.1) +
  # geom_point(data = s6_ctd_mark, aes(x = lat, y = z), colour = "Black", size = 0.4, shape = 3, alpha = 0.1) +
  scale_fill_gradientn(colors = odv.colors) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("Depth, m")), x = expression(italic("")), fill = expression(italic(paste("z-score")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1)) +
  theme(legend.spacing.y = unit(0.5, 'cm')) +
  custom_theme() +
  ggtitle("Beam Transmission")



```

## Fluoresence

```{r}

subset <- ctd %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, fl_mg_m3) %>% 
  group_by(z) %>% 
  mutate(mean = mean(fl_mg_m3),
         sd = sd(fl_mg_m3),
         zscore = (fl_mg_m3 - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z > 0)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z > 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

fl.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) +
  geom_raster(aes(fill = zscore)) +
  geom_vline(aes(xintercept = 47.25), linetype = 2, size = 2) +
  geom_vline(aes(xintercept = 47.75), linetype = 2, size = 2) +
  geom_point(data = subset, aes(x = lat, y = z), colour = "White", size = 0.4, shape = 3, alpha = 0.1) +
  # geom_point(data = s4_ctd_mark, aes(x = lat, y = z), colour = "Black", size = 0.4, shape = 3, alpha = 0.1) +
  # geom_point(data = s6_ctd_mark, aes(x = lat, y = z), colour = "Black", size = 0.4, shape = 3, alpha = 0.1) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("Depth, m")), x = expression(italic("")), fill = expression(italic(paste("")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1)) +
  theme(legend.spacing.y = unit(0.5, 'cm')) +
  custom_theme() +
  ggtitle("Fluorescence")

```

## Phytoplankton Abundance

```{r}

subset <- data %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, phyto) %>% 
  group_by(z) %>% 
  mutate(mean = mean(phyto, na.rm = T),
         sd = sd(phyto, na.rm = T),
         zscore = (phyto - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z >= 0) %>% 
  drop_na(zscore)

s4_mark <- s4_data_mark %>% 
  drop_na(phyto)

s6_mark <- s6_data_mark %>% 
  drop_na(phyto)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z >= 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

phyto.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
  geom_raster(aes(fill = zscore)) +
  geom_vline(aes(xintercept = 47.25), linetype = 2, size = 2) +
  geom_vline(aes(xintercept = 47.75), linetype = 2, size = 2) +
  geom_point(data = subset, aes(x = lat, y = z), colour = "White", size = 2, shape = 3, alpha = 0.6) +
  # geom_point(data = s4_mark, aes(x = lat, y = z), colour = "Black", size = 2, shape = 3, alpha = 0.6) +
  # geom_point(data = s6_mark, aes(x = lat, y = z), colour = "Black", size = 2, shape = 3, alpha = 0.6) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("Depth, m")), x = expression(italic("Latitude,˚N")), fill = expression(italic(paste("")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1)) +
  theme(legend.spacing.y = unit(0.5, 'cm')) +
  custom_theme() +
  ggtitle("Phytoplankton Abundance")

```

## NPP

```{r}

subset <- npp %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, npp) %>% 
  group_by(z) %>% 
  mutate(mean = mean(npp, na.rm = T),
         sd = sd(npp, na.rm = T),
         zscore = (npp - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z >= 0) %>% 
  drop_na(zscore)

s4_mark <- npp %>% 
  filter(between(z, 0, 300)) %>% 
  filter(Cruise == "AT34", Station == 4) %>% 
  select(lat, z) %>% 
  distinct() 

s6_mark <- npp %>% 
  filter(between(z, 0, 300)) %>% 
  filter(Cruise == "AT38", Station == 6) %>% 
  select(lat, z) %>% 
  distinct() 

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z >= 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

npp.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
  geom_raster(aes(fill = zscore)) +
  geom_vline(aes(xintercept = 47.25), linetype = 2, size = 2) +
  geom_vline(aes(xintercept = 47.75), linetype = 2, size = 2) +
  geom_point(data = subset, aes(x = lat, y = z), colour = "White", size = 0.4, shape = 3, alpha = 0.3) +
  # geom_point(data = s4_mark, aes(x = lat, y = z), colour = "Black", size = 0.4, shape = 3, alpha = 0.3) +
  # geom_point(data = s6_mark, aes(x = lat, y = z), colour = "Black", size = 0.4, shape = 3, alpha = 0.3) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("")), x = expression(italic("")), fill = expression(italic(paste("")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1)) +
  theme(legend.spacing.y = unit(0.5, 'cm')) +
  custom_theme() +
  ggtitle("Modeled NPP")

```


## Bacterial Abundance

```{r}

subset <- data %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, ba) %>% 
  group_by(z) %>% 
  mutate(mean = mean(ba, na.rm = T),
         sd = sd(ba, na.rm = T),
         zscore = (ba - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z >= 0) %>% 
  drop_na(zscore)

s4_mark <- s4_data_mark %>% 
  drop_na(ba)

s6_mark <- s6_data_mark %>% 
  drop_na(ba)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z >= 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

ba.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
  geom_raster(aes(fill = zscore)) +
  geom_vline(aes(xintercept = 47.25), linetype = 2, size = 2) +
  geom_vline(aes(xintercept = 47.75), linetype = 2, size = 2) +
 geom_point(data = subset, aes(x = lat, y = z), colour = "White", size = 2, shape = 3, alpha = 0.6) +
  # geom_point(data = s4_mark, aes(x = lat, y = z), colour = "Black", size = 2, shape = 3, alpha = 0.6) +
  # geom_point(data = s6_mark, aes(x = lat, y = z), colour = "Black", size = 2, shape = 3, alpha = 0.6) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("")), x = expression(italic("")), fill = expression(italic(paste("z-score")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1)) +
  theme(legend.spacing.y = unit(0.5, 'cm')) +
  custom_theme() +
  ggtitle("Bacterioplankton Abundance")

```

## BCD

```{r}

subset <- data %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, bcd) %>% 
  group_by(z) %>% 
  mutate(mean = mean(bcd, na.rm = T),
         sd = sd(bcd, na.rm = T),
         zscore = (bcd - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z >= 0) %>% 
  drop_na(zscore)

s4_mark <- s4_data_mark %>% 
  drop_na(bcd)

s6_mark <- s6_data_mark %>% 
  drop_na(bcd)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z >= 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

bcd.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
  geom_raster(aes(fill = zscore)) +
  geom_vline(aes(xintercept = 47.25), linetype = 2, size = 2) +
  geom_vline(aes(xintercept = 47.75), linetype = 2, size = 2) +
  geom_point(data = subset, aes(x = lat, y = z), colour = "White", size = 2, shape = 3, alpha = 0.6) +
  # geom_point(data = s4_mark, aes(x = lat, y = z), colour = "Black", size = 2, shape = 3, alpha = 0.6) +
  # geom_point(data = s6_mark, aes(x = lat, y = z), colour = "Black", size = 2, shape = 3, alpha = 0.6) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("")), x = expression(italic("Latitude, ˚N")), fill = expression(italic(paste("")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1)) +
  theme(legend.spacing.y = unit(0.5, 'cm')) +
  custom_theme() +
  ggtitle("Bacterioplankton Carbon Demand")

```




## N + N

```{r}

subset <- data %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, n) %>% 
  group_by(z) %>% 
  mutate(mean = mean(n, na.rm = T),
         sd = sd(n, na.rm = T),
         zscore = (n - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z >= 0) %>% 
  drop_na(zscore)

s4_mark <- s4_data_mark %>% 
  drop_na(n)

s6_mark <- s6_data_mark %>% 
  drop_na(n)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z >= 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

n.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
  geom_raster(aes(fill = zscore)) +
  geom_vline(aes(xintercept = 47.25), linetype = 2, size = 2) +
  geom_vline(aes(xintercept = 47.75), linetype = 2, size = 2) +
  geom_point(data = subset, aes(x = lat, y = z), colour = "White", size = 2, shape = 3, alpha = 0.6) +
  # geom_point(data = s4_mark, aes(x = lat, y = z), colour = "Black", size = 2, shape = 3, alpha = 0.6) +
  # geom_point(data = s6_mark, aes(x = lat, y = z), colour = "Black", size = 2, shape = 3, alpha = 0.6) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("")), x = expression(italic("")), fill = expression(italic(paste("z-score")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1)) +
  theme(legend.spacing.y = unit(0.5, 'cm')) +
  custom_theme() +
  ggtitle("N + N")

```


## DOC

```{r}

subset <- data %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, doc) %>% 
  group_by(z) %>% 
  mutate(mean = mean(doc, na.rm = T),
         sd = sd(doc, na.rm = T),
         zscore = (doc - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z >= 0) %>% 
  drop_na(zscore)

s4_mark <- s4_data_mark %>% 
  drop_na(doc)

s6_mark <- s6_data_mark %>% 
  drop_na(doc)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z >= 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

doc.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
  geom_raster(aes(fill = zscore)) +
  geom_vline(aes(xintercept = 47.25), linetype = 2, size = 2) +
  geom_vline(aes(xintercept = 47.75), linetype = 2, size = 2) +
  geom_point(data = subset, aes(x = lat, y = z), colour = "White", size = 2, shape = 3, alpha = 0.6) +
  # geom_point(data = s4_mark, aes(x = lat, y = z), colour = "Black", size = 2, shape = 3, alpha = 0.6) +
  # geom_point(data = s6_mark, aes(x = lat, y = z), colour = "Black", size = 2, shape = 3, alpha = 0.6) +
  #geom_line(data = mld.odv, aes(x = decimaldate, y = MLD), colour = "White", linetype = 2, size = 1 ) +
   # geom_point(data = mld.odv, aes(x = decimaldate, y = MLD), colour = "White", shape = 19, size = 3, alpha = 0.8) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("")), x = expression(italic("")), fill = expression(italic(paste("")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1)) +
  theme(legend.spacing.y = unit(0.5, 'cm')) +
  custom_theme() +
  ggtitle("DOC")

```


## AOU

```{r}

subset <- ctd %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, deriv_aou_umol_kg) %>% 
  rename(aou = deriv_aou_umol_kg) %>% 
  group_by(z) %>% 
  mutate(mean = mean(aou, na.rm = T),
         sd = sd(aou, na.rm = T),
         zscore = (aou - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z >= 0) %>% 
  drop_na(zscore)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z >= 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

aou.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
  geom_raster(aes(fill = zscore)) +
  geom_vline(aes(xintercept = 47.25), linetype = 2, size = 2) +
  geom_vline(aes(xintercept = 47.75), linetype = 2, size = 2) +
  geom_point(data = subset, aes(x = lat, y = z), colour = "White", size = 0.4, shape = 3, alpha = 0.1) +
  # geom_point(data = s4_ctd_mark, aes(x = lat, y = z), colour = "Black", size = 0.4, shape = 3, alpha = 0.1) +
  # geom_point(data = s6_ctd_mark, aes(x = lat, y = z), colour = "Black", size = 0.4, shape = 3, alpha = 0.1) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("")), x = expression(italic("Latitude, ˚N")), fill = expression(italic(paste("")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1)) +
  theme(legend.spacing.y = unit(0.5, 'cm')) +
  custom_theme() +
  ggtitle("AOU")

```

### Patchwork

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 20, fig.width = 34, fig.align = "center", warning = FALSE}

patchwork <- (beamt.plot / fl.plot / phyto.plot) | (ba.plot / npp.plot / bcd.plot) | (n.plot / doc.plot / aou.plot )

patchwork +  plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(size = 22))

```











