---
title: "Plots"
author: "Nicholas Baetge"
date: "8/6/2020"
output: html_document
---
# Intro

Here, data are are plotted for two multiday stations, N2S4 and N3S6


```{r message = F, warning = F}
library(tidyverse) 
library(rmarkdown)
library(knitr)
library(readxl)
library(data.table) 
library(scales)
library(zoo)
library(oce)
library(patchwork)
#rmarkdown tables
library(stargazer)
library(pander)
#stat tests
library(lmtest)
library(lmodel2)
library(rstatix)
library(ggpubr)
#for odv type plots
library(lubridate)
library(reshape2)
library(MBA)
library(mgcv)

custom_theme <- function() {
  theme_test(base_size = 30) %+replace%
    theme(legend.position = "right",
          legend.spacing.x = unit(0.5,"cm"),
          legend.title = element_text(size = 14),
          legend.text = element_text(size = 14),
          legend.background = element_rect(fill = "transparent",colour = NA),
          legend.key = element_rect(fill = "transparent",colour = NA),
          panel.background = element_rect(fill = "transparent",colour = NA),
          plot.background = element_rect(fill = "transparent",colour = NA)) 
}

custom.colors <- c("AT39" = "#377EB8", "AT34" = "#4DAF4A", "AT38" = "#E41A1C", "AT32" = "#FF7F00", "Temperate" = "#A6CEE3", "Subpolar" = "#377EB8", "Subtropical" = "#FB9A99", "GS/Sargasso" = "#E41A1C", "Early Spring" = "#377EB8", "Late Spring" = "#4DAF4A","Early Autumn" = "#E41A1C", "Summer" = "#E41A1C", "Late Autumn" = "#FF7F00", "Gv2_2019" = "#377EB8", "WOA18_MN" = "#4DAF4A", "WOA18_AN" = "#E41A1C")

levels = c("GS/Sargasso", "Subtropical", "Temperate", "Subpolar",  "AT39-6", "AT34", "AT38", "AT32","South", "North", "Early Spring", "Late Spring","Early Autumn",  "Summer", "Late Autumn", "Gv2_2019", "WOA18_MN", "WOA18_AN","Nov", "Nov sd", "Dec", "Dec sd", "Jan", "Jan sd", "Feb", "Feb sd", "Mar", "Mar sd", "Apr", "Apr sd",  "Cruise", "ARGO")

bar.colors <- c("100 m" = "white", "CM" = "#4DAF4A",  "PAM" = "#377EB8")

odv.colors <- c("#feb483", "#d31f2a", "#ffc000", "#27ab19", "#0db5e6", "#7139fe", "#d16cfa")
```

# Import Data

```{r}
data <- read_rds("~/GITHUB/naames_multiday/Output/processed_data.df")

ctd <- read_rds("~/GITHUB/naames_multiday/Input/ctd/deriv_naames_ctd.rds") %>% 
  rename(lat = "Latitude [degrees_north]",
         z = bin_depth) %>% 
  mutate(bin = round(lat, 1))
```

# Plot ODV-style composites

## BeamT

```{r}

subset <- ctd %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, beamT_perc) %>% 
  group_by(z) %>% 
  mutate(mean = mean(beamT_perc),
         sd = sd(beamT_perc),
         zscore = (beamT_perc - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z > 0)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z > 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

beamt.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
   
  geom_raster(aes(fill = zscore)) +
 geom_point(data = subset, aes(x = lat, y = z), colour = "Black", size = 0.05, shape = 3, alpha = 0.1) +
  #geom_line(data = mld.odv, aes(x = decimaldate, y = MLD), colour = "White", linetype = 2, size = 1 ) +
   # geom_point(data = mld.odv, aes(x = decimaldate, y = MLD), colour = "White", shape = 19, size = 3, alpha = 0.8) +
  scale_fill_gradientn(colors = odv.colors) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("Depth, m")), x = expression(italic("Latitude, ˚N")), fill = expression(italic(paste("Beam T., \n z-score")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2)) +
  custom_theme() 

beamt.plot


```

## Fluoresence

```{r}

subset <- ctd %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, fl_mg_m3) %>% 
  group_by(z) %>% 
  mutate(mean = mean(fl_mg_m3),
         sd = sd(fl_mg_m3),
         zscore = (fl_mg_m3 - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z > 0)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z > 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

fl.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
   
  geom_raster(aes(fill = zscore)) +
 geom_point(data = subset, aes(x = lat, y = z), colour = "Black", size = 0.05, shape = 3, alpha = 0.1) +
  #geom_line(data = mld.odv, aes(x = decimaldate, y = MLD), colour = "White", linetype = 2, size = 1 ) +
   # geom_point(data = mld.odv, aes(x = decimaldate, y = MLD), colour = "White", shape = 19, size = 3, alpha = 0.8) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("Depth, m")), x = expression(italic("Latitude, ˚N")), fill = expression(italic(paste("Fluor., \n z-score")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2)) +
  custom_theme() 

fl.plot


```

## Bacterial Abundance

```{r}

subset <- data %>% 
  rename(lat = Latitude) %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, ba) %>% 
  group_by(z) %>% 
  mutate(mean = mean(ba, na.rm = T),
         sd = sd(ba, na.rm = T),
         zscore = (ba - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z > 0) %>% 
  drop_na(zscore)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z > 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

ba.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
   
  geom_raster(aes(fill = zscore)) +
 geom_point(data = subset, aes(x = lat, y = z), colour = "Black", size = 0.5, shape = 3, alpha = 0.5) +
  #geom_line(data = mld.odv, aes(x = decimaldate, y = MLD), colour = "White", linetype = 2, size = 1 ) +
   # geom_point(data = mld.odv, aes(x = decimaldate, y = MLD), colour = "White", shape = 19, size = 3, alpha = 0.8) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("Depth, m")), x = expression(italic("Latitude, ˚N")), fill = expression(italic(paste("BA, \n z-score")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2)) +
  custom_theme() 

ba.plot


```

## BCD

```{r}

subset <- data %>% 
  rename(lat = Latitude) %>% 
  filter(between(z, 0, 300)) %>% 
  select(lat, z, bcd) %>% 
  group_by(z) %>% 
  mutate(mean = mean(bcd, na.rm = T),
         sd = sd(bcd, na.rm = T),
         zscore = (bcd - mean)/sd) %>% 
  ungroup() %>% 
  select(lat, z, zscore) %>% 
  mutate(zscore = round(zscore, 2)) %>% 
  filter(z > 0) %>% 
  drop_na(zscore)

mba <- mba.surf(subset, no.X = 300, no.Y = 300, extend = F)
dimnames(mba$xyz.est$z) <- list(mba$xyz.est$x, mba$xyz.est$y)
mba <- melt(mba$xyz.est$z, varnames = c('lat', 'z'), value.name = 'zscore') %>%
  filter(z > 0) 

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 6, fig.width = 12, fig.align = "center", warning = FALSE}

bcd.plot <-  mba %>% 
  ggplot(aes(x = lat, y = z)) + 
   
  geom_raster(aes(fill = zscore)) +
 geom_point(data = subset, aes(x = lat, y = z), colour = "Black", size = 0.5, shape = 3, alpha = 0.5) +
  #geom_line(data = mld.odv, aes(x = decimaldate, y = MLD), colour = "White", linetype = 2, size = 1 ) +
   # geom_point(data = mld.odv, aes(x = decimaldate, y = MLD), colour = "White", shape = 19, size = 3, alpha = 0.8) +
  scale_fill_gradientn(colors = rev(odv.colors)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  scale_x_continuous(breaks = pretty_breaks()) +
  labs(y = expression(italic("Depth, m")), x = expression(italic("Latitude, ˚N")), fill = expression(italic(paste("BCD, \n z-score")))) +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2)) +
  custom_theme() 

bcd.plot


```