---
title: "Depth_Profiles"
author: "Nicholas Baetge"
date: "8/6/2020"
output: github_document
---

# Intro

Here, we plot the profiles from the multiday NAAMES station, N2S4.

```{r message = F, warning = F}
library(tidyverse) 
library(rmarkdown)
library(knitr)
library(readxl)
library(data.table) 
library(scales)
library(zoo)
library(oce)
library(patchwork)
#rmarkdown tables
library(stargazer)
library(pander)
#stat tests
library(lmtest)
library(lmodel2)
library(rstatix)
library(ggpubr)
library(lubridate)


```

```{r}
custom_theme <- function() {
  theme_test(base_size = 30) %+replace%
    theme(legend.position = "right",
          legend.spacing.x = unit(0.5,"cm"),
          legend.title = element_text(size = 14),
          legend.text = element_text(size = 14),
          legend.background = element_rect(fill = "transparent",colour = NA),
          legend.key = element_rect(fill = "transparent",colour = NA),
          panel.background = element_rect(fill = "transparent",colour = NA),
          plot.background = element_rect(fill = "transparent",colour = NA)) 
}

custom.colors <- c("AT39" = "#377EB8", "AT34" = "#4DAF4A", "AT38" = "#E41A1C", "AT32" = "#FF7F00", "Temperate" = "#A6CEE3", "Subpolar" = "#377EB8", "Subtropical" = "#FB9A99", "GS/Sargasso" = "#E41A1C", "Early Spring" = "#377EB8", "Late Spring" = "#4DAF4A","Early Autumn" = "#E41A1C", "Late Autumn" = "#FF7F00")

levels = c("GS/Sargasso", "Subtropical", "Temperate", "Subpolar",  "AT39-6", "AT34", "AT38", "AT32","South", "North", "Early Spring", "Late Spring","Early Autumn",  "Late Autumn")

odv.colors <- c("#feb483", "#d31f2a", "#ffc000", "#27ab19", "#0db5e6", "#7139fe", "#d16cfa")
```

# Import Data

```{r message = F, warning = F}
data <- read_rds("~/GITHUB/naames_multiday/Output/processed_data.rds") %>% 
  filter(Cruise == "AT34" & Station == 4 | Cruise == "AT38" & Station == 6) %>% 
  mutate_at(vars(contains("tdaa"), Asp:Lys), funs(. / 10^3)) %>% #nM to mmol/m3
  mutate(tdaa_yield = round((tdaa_c/doc)*100, 2),
         eddy = ifelse(Date != "2016-05-27" & Station != 6, "Core", "Outside")) 

npp <- read_rds("~/GITHUB/naames_multiday/Input/Z_resolved_model_NPP.rds") %>% 
  rename(z = depth,
         npp = NPP) %>% 
  mutate(npp = round((npp * 10^3)/12),
         eddy = ifelse(Date != "2016-05-27" & Station != 6, "Core", "Outside")) %>% 
  filter(Cruise == "AT34" & Station == 4 | Cruise == "AT38" & Station == 6)  

ctd <-  read_rds("~/GITHUB/naames_multiday/Input/ctd/deriv_naames_ctd.rds") %>% 
  rename(lat = "Latitude [degrees_north]",
         z = bin_depth) %>% 
  mutate(bin = round(lat, 1),
         Date = ymd_hm(`yyyy-mm-ddThh:mm:ss.sss`),
         Date = as_date(round_date(Date, unit = "day")),
         eddy = ifelse(Date != "2016-05-27" & Station != 6, "Core", "Outside")) %>% 
  filter(Cruise == "AT34" & Station == 4 | Cruise == "AT38" & Station == 6)

casts <- data %>% 
  filter(Cruise == "AT34", Date != "2016-05-27") %>% 
  distinct(CampCN) %>% 
  as_vector()

```

# Station 4

## Plot MLDs

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center"}
mld.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(mld) %>% 
  # group_by(Date) %>% 
  # mutate(mean_mld = mean(mld, na.rm = T),
  #        sd_mld = sd(mld, na.rm = T)) %>% 
  # µg / L = mg / m3
  ggplot(aes(x = datetime, y = mld)) +
  geom_line(aes(linetype = eddy), size = 0.7) +
  geom_point(aes(shape = eddy), size = 6, fill = "white", color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("MLD, m"))), colour = "", linetype = "Eddy Location", shape = "Eddy Location") +
  guides(linetype = F, shape = F) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_y_reverse(breaks = pretty_breaks()) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.key.size = unit(1, "cm"))
  
  mld.plot

```

## Plot T/S

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 7, fig.width = 18, fig.align = "center"}

ts.data <- ctd %>% 
  filter(Cruise == "AT34" & CampCN <= 66) %>% 
  select(Date, CampCN, z, deriv_potT_c, ave_sal_psu) %>% 
  arrange(CampCN, z) %>% 
  filter(z <= 300) %>% 
  rename(sal = ave_sal_psu,
         pot.temp = deriv_potT_c)

# make TS long table
TS <- expand.grid(sal = seq(floor(min(ts.data$sal, na.rm = TRUE)), ceiling(max(ts.data$sal, na.rm = TRUE)), length.out = 100),
                   pot.temp = seq(floor(min(ts.data$pot.temp, na.rm = TRUE)), ceiling(max(ts.data$pot.temp, na.rm = TRUE)), length.out = 100)
  )
TS$density <- gsw_rho_t_exact(SA = TS$sal, t = TS$pot.temp, p = 0) - 1000 # the function calculates in-situ density, but because potential temperature and a single reference pressure is used the result equals potential density at reference pressure

# vertical isopycnal labels
v.isopycnals <- subset(TS, # make a df for labeling vertical isopycnals
                       pot.temp == ceiling(max(TS$pot.temp)) & # selects all rows where "sal" is the max limit of the x axis
                         round(density,1) %in% seq(min(round(TS$density*2)/2),
                                                   max(round(TS$density*2)/2),
                                                   by = .5)) # selects any line where the rounded denisty is equal to density represented by any isopycnal in the plot
v.isopycnals$density <- round(v.isopycnals$density, 1) # rounds the density
v.isopycnals <- aggregate(sal~density, v.isopycnals, mean) # reduces number of "pot.temp" values to 1 per each unique "density" value

 
ts.plot <- ggplot() +
  geom_contour(data = TS, aes(x = sal, y = pot.temp, z = density), col = "grey", linetype = "dashed", breaks = seq(min(round(TS$density*2)/2, na.rm = TRUE), # taking density times 2, rounding and dividing by 2 rounds it to the neares 0.5
max(round(TS$density*2)/2, na.rm = TRUE),  by = .25)) +
  geom_point(data = ts.data, # plot only the points that have a z value in color according to z 
             aes(sal, pot.temp, color = z)) +
  annotate(geom = "text", x = floor(min(TS$sal, na.rm = TRUE)), y = ceiling(max(TS$pot.temp, na.rm = TRUE)), hjust = "inward", vjust = "inward", color = "grey60", size = 14, label = paste0('sigma',"[",0,"]"), parse = T) +
  scale_x_continuous(expand = c(0,0), limits = c(floor(min(TS$sal, na.rm = TRUE)), ceiling(max(TS$sal, na.rm = TRUE)))) + # use range of "sal" for x axis
  scale_y_continuous(limits = c(floor(min(TS$pot.temp, na.rm = TRUE)), ceiling(max(TS$pot.temp, na.rm = TRUE)))) + # use range of "pot.temp" for y axis
  scale_color_gradientn(colors = odv.colors) +
  labs(x = expression(italic(paste("Salinity, psu"))), y = expression(italic(paste("Potential Temperature, ˚C"))), color = "Depth, m") +
  custom_theme() + 
  facet_grid(~Date) +
  theme(panel.spacing = unit(4, "lines"),
        legend.spacing.y = unit(0.5, 'cm')) +
  guides(color = guide_colorbar(frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1))


ts.plot + geom_text(data = v.isopycnals, aes(x = sal, y = ceiling(max(TS$pot.temp)), label = density), vjust = "inward", hjust = 0, col = "grey")
  
```


## Plot Profiles 

### Chl

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
chl.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(chl) %>% 
  # µg / L = mg / m3
  filter(z %in% c(0, 5, 10, 25, 50, 75, 100, 150, 200, 300)) %>% 
  ggplot(aes(x = z, y = chl, group = interaction(Date, CampCN))) +
  geom_line(aes(linetype = eddy, color = Date), size = 0.7) +
  geom_point(aes(shape = eddy, fill = Date), size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste("Depth, m"))), y = expression(italic(paste("Chl a, mg m"^"-3"))), colour = "", fill = "", linetype = "Eddy Location", shape = "Eddy Location") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  guides(fill = guide_colourbar(barheight = 20, barwidth = 2, frame.colour = "black", frame.linewidth = 2,ticks.colour = "black", ticks.linewidth = 1), color = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.key.size = unit(1, "cm"))

```

### Phyto Cells

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
phyto.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(phyto) %>% 
  mutate(phyto = phyto * 10^3) %>% 
  group_by(Date, z) %>% 
  mutate_at(vars(pro:nano, phyto:rel.nano), mean) %>% 
  select(Date,  z, phyto, eddy) %>% 
  distinct() %>% 
  filter(z %in% c(0, 5, 10, 25, 50, 75, 100, 150, 200, 300)) %>% 
  ggplot(aes(x = z, y = phyto, group = interaction(Date))) +
  geom_line(aes(linetype = eddy, colour = Date), size = 0.7) +
  geom_point(aes(shape = eddy, fill = Date), size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste("Depth, m"))), y = expression(italic(paste("Phytoplankton Cells, m"^"-3"))), colour = "", linetype = "Eddy Location", shape = "Eddy Location") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  guides(colour = F, fill = F, shape = F, linetype = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.key.size = unit(1, "cm")) 
```


### PhytoC

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
phyc.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(phyc) %>%
 filter(z %in% c(0, 5, 10, 25, 50, 75, 100, 150, 200, 300)) %>% 
  group_by(Date, z) %>% 
  mutate(phyc = phyc / 10^3,
         ave_phyc = mean(phyc, na.rm = T), 
         sd_phyc = sd(phyc, na.rm = T)) %>%
  ungroup() %>% 
  ggplot(aes(x = z, y = ave_phyc, group = interaction(Date, CampCN))) +
  geom_errorbar(aes(ymin = ave_phyc - sd_phyc, ymax = ave_phyc + sd_phyc, color = Date), width = 1.5, alpha = 0.7) +
  geom_line(aes(linetype = eddy, colour = Date), size = 0.7) +
  geom_point(aes(shape = eddy, fill = Date), size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste("Depth, m"))), y = expression(italic(paste("Phytoplankton Carbon, mmol m"^"-3"))), colour = "", linetype = "Eddy Location", shape = "Eddy Location") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  guides(colour = F, fill = F, shape = F, linetype = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0))

```

### NPP

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
npp.plot <-  npp %>% 
  filter(Cruise == "AT34") %>% 
  mutate(npp = npp/10^3) %>% 
  ggplot(aes(x = z, y = npp, group = Date)) +
  geom_line(aes(linetype = eddy, colour = Date), size = 2) +
  # geom_point(aes(fill = Date), size = 6, shape = 21, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste("Depth, m"))), y = expression(italic(paste("Modeled NPP, mmol m"^-3, "d"^-1))), colour = "", linetype = "Eddy Location", shape = "Eddy Location") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  guides(colour = F, fill = F, shape = F, linetype = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0))

```



### N

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
n.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(n) %>% 
  filter(z %in% c(0, 5, 10, 25, 50, 75, 100, 150, 200, 300)) %>% 
  ggplot(aes(x = z, y = n, group = interaction(Date, CampCN))) +
  geom_errorbar(aes(x = z, ymin = n - sd_n, ymax = n + sd_n)) +
  geom_line(aes(linetype = eddy, color = Date), size = 0.7) +
  geom_point(aes(shape = eddy, fill = Date), size = 6,  color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("N + N, mmol m"^"-3"))), colour = "", linetype = "Eddy Location", shape = "Eddy Location", fill = "") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  guides(colour = F, fill = F, shape = F, linetype = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.key.size = unit(1, "cm"))

```


### DOC

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
doc.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(doc) %>% 
  filter(z %in% c(0, 5, 10, 25, 50, 75, 100, 150, 200, 300)) %>% 
  ggplot(aes(x = z, y = doc, group = interaction(Date, CampCN))) +
  geom_errorbar(aes(x = z, ymin = doc - sd_doc, ymax = doc + sd_doc, color = Date)) +
  geom_line(aes(linetype = eddy, color = Date), size = 0.7) +
  geom_point(aes(shape = eddy, fill = Date), size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("DOC, mmol m"^"-3"))), colour = "", linetype = "Eddy Location", shape = "Eddy Location") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  guides(fill = F, color = F, linetype = F, shape = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank())

```

### TDAA

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
tdaa.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(tdaa_c) %>% 
  filter(z %in% c(0, 5, 10, 25, 50, 75, 100, 150, 200, 300)) %>% 
  ggplot(aes(x = z, y = tdaa_c, group = interaction(Date, CampCN))) +
  geom_errorbar(aes(x = z, ymin = tdaa_c - sd_tdaa, ymax = tdaa_c + sd_tdaa, color = Date)) +
  geom_line(aes(linetype = eddy, color = Date), size = 0.7) +
  geom_point(aes(shape = eddy, fill = Date), size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("TDAA, mmol C m"^-3))), colour = "", linetype = "Eddy Location", shape = "Eddy Location") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  guides(fill = F, color = F, linetype = F, shape = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank())

```


### TDAA Yield

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
tdaaY.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(tdaa_yield) %>% 
  filter(z %in% c(0, 5, 10, 25, 50, 75, 100, 150, 200, 300)) %>% 
  ggplot(aes(x = z, y = tdaa_yield, group = interaction(Date, CampCN))) +
  geom_line(aes(linetype = eddy, color = Date), size = 0.7) +
  geom_point(aes(shape = eddy, fill = Date), size = 6, shape = 21, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("TDAA Yield, %"))), colour = "", linetype = "Eddy Location", shape = "Eddy Location") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  guides(fill = F, color = F, linetype = F, shape = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank())

```




### AOU

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
aou.plot <-  ctd %>% 
  filter(Cruise == "AT34", Date != "2016-05-28") %>% 
  filter(z <= 300) %>% 
  group_by(Date, z) %>% 
  mutate(ave_aou = mean(deriv_aou_umol_kg, na.rm = T),
         sd_aou = sd(deriv_aou_umol_kg, na.rm = T)) %>% 
  ungroup() %>% 
  ggplot(aes(x = z, y = ave_aou, group = interaction(Date, CampCN))) +
  geom_ribbon(aes(ymin = ave_aou - sd_aou, ymax = ave_aou + sd_aou, fill = Date, linetype = eddy), alpha = 0.1) +
  geom_line(aes(linetype = eddy, color = Date), size = 0.7) +
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("AOU, mmol m"^"-3"))), colour = "", linetype = "Eddy Location", shape = "Eddy Location") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  guides(colour = F, fill = F, shape = F, linetype = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank())

```




### BactC

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
bc.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(bc) %>% 
  mutate(bc = bc / 10^3,
         sd_bc = sd_bc/10^3) %>% 
  filter(z %in% c(0, 5, 10, 25, 50, 75, 100, 150, 200, 300)) %>% 
  ggplot(aes(x = z, y = bc, group = interaction(Date, CampCN))) +
  geom_errorbar(aes(x = z, ymin = bc - sd_bc, ymax = bc + sd_bc, color = Date)) +
  geom_line(aes(linetype = eddy, color = Date), size = 0.7) +
  geom_point(aes(shape = eddy, fill = Date), size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("BC, mmol C m"^"-3"))), colour = "", linetype = "Eddy Location", shape = "Eddy Location", fill = "") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  guides(colour = F, fill = F, shape = F, linetype = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.key.size = unit(1, "cm"))

```

### BCD

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
bcd.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(bcd) %>% 
  filter(z %in% c(0, 5, 10, 25, 50, 75, 100, 150, 200, 300)) %>% 
  mutate(bcd = bcd/10^3,
         sd_bcd = sd_bp/10^3) %>% 
  ggplot(aes(x = z, y = bcd, group = interaction(Date, CampCN))) +
  geom_errorbar(aes(x = z, ymin = bcd - sd_bcd, ymax = bcd + sd_bcd, color = Date)) +
  geom_line(aes(linetype = eddy, color = Date), size = 0.7) +
  geom_point(aes(shape = eddy, fill = Date), size = 6, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("BCD, mmol C m"^"-3","d"^-1))), colour = "", linetype = "Eddy Location", shape = "Eddy Location") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  guides(fill = F, color = F, linetype = F, shape = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank())

```

### µ

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 20, fig.align = "center", warning = FALSE}
mew.plot <-  data %>% 
  filter(Cruise == "AT34") %>% 
  drop_na(mew) %>% 
  filter(z %in% c(0, 5, 10, 25, 50, 75, 100, 150, 200, 300)) %>% 
  ggplot(aes(x = z, y = mew, group = interaction(Date, CampCN))) +
  geom_errorbar(aes(x = z, ymin = mew - mew.error, ymax = mew + mew.error)) +
  geom_line(aes(color = Date), size = 0.7) +
  geom_point(aes(fill = Date), size = 6, shape = 21, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("µ, d"^-1))), colour = "") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_date(low = "#0db5e6", high = "#d31f2a") +
  scale_color_date(low = "#0db5e6", high = "#d31f2a") +
  guides(colour = F, fill = F, shape = F, linetype = F) +
  custom_theme() +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 0),
        legend.title = element_blank())

```


```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 20, fig.width = 22, fig.align = "center"}

patchwork <- (mld.plot  / chl.plot / phyc.plot / phyto.plot ) | (npp.plot / n.plot / aou.plot / doc.plot ) | (tdaa.plot / tdaaY.plot / bc.plot / bcd.plot)

patchwork +  
  plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(size = 22)) 

```





