---
title: "S4 Integration Plots"
author: "Nicholas Baetge"
date: "8/12/2020"
output: github_document
---

# Intro

Here, we plot the integrated from the multiday NAAMES station, N2S4.

```{r load packages, message = F, warning = F}
library(tidyverse)
library(lubridate)
library(patchwork)
```

```{r aesthetics}
custom_theme <- function() {
  theme_test(base_size = 30) %+replace%
    theme(legend.position = "right",
          legend.spacing.x = unit(0.5,"cm"),
          legend.title = element_text(size = 14),
          legend.text = element_text(size = 14),
          legend.background = element_rect(fill = "transparent",colour = NA),
          legend.key = element_rect(fill = "transparent",colour = NA),
          panel.background = element_rect(fill = "transparent",colour = NA),
          plot.background = element_rect(fill = "transparent",colour = NA)) 
}

custom.colors <- c("AT39" = "#377EB8", "AT34" = "#4DAF4A", "AT38" = "#E41A1C", "AT32" = "#FF7F00", "Temperate" = "#A6CEE3", "Subpolar" = "#377EB8", "Subtropical" = "#FB9A99", "GS/Sargasso" = "#E41A1C", "Early Spring" = "#377EB8", "Late Spring" = "#4DAF4A","Early Autumn" = "#E41A1C", "Late Autumn" = "#FF7F00",  "0 - 75 m" = "#27ab19", "75 - 100 m" = "#feb483", "100 - 300 m" = "#d16cfa")

levels = c("GS/Sargasso", "Subtropical", "Temperate", "Subpolar",  "AT39-6", "AT34", "AT38", "AT32","South", "North", "Early Spring", "Late Spring","Early Autumn",  "Late Autumn", "0 - 75 m", "75 - 100 m", "100 - 300 m")

odv.colors <- c("#feb483", "#d31f2a", "#ffc000", "#27ab19", "#0db5e6", "#7139fe", "#d16cfa")
```


# Import Data

```{r import data, message=FALSE, warning=FALSE}
data <- read_rds("~/GITHUB/naames_multiday/Output/processed_data.rds") %>% 
  filter(Cruise == "AT34" & Station == 4) %>% 
  mutate(time = ymd_hms(datetime),
         interv = interval(first(time), time),
         dur = as.duration(interv),
         days = as.numeric(dur, "days"),
         eddy = ifelse(Date != "2016-05-27", "Core", "Outside")) %>% 
  select(Cruise, Station, Date, eddy, time:days, bcd.75:npp.300) %>% 
  distinct() %>% 
  mutate_at(vars(contains(c("phyc", "npp", "bc"))), function(x) (x / 1000)) %>%
  mutate(bc_phyc.75 = bc.75/phyc.75,
         bc_phyc.100 = bc.100/phyc.100,
         bc_phyc.300 = bc.300/phyc.300,
         bcd_phyc.75 = bcd.75/phyc.75,
         bcd_phyc.100 = bcd.100/phyc.100,
         bcd_phyc.300 = bcd.300/phyc.300
         ) %>% 
   mutate_at(vars(contains("tdaa")), funs(. / 10^3)) #nM to mmol/m3

```

# Pivot data

```{r pivot data, message=FALSE, warning=FALSE}
pivot_phyc_data <- data %>% 
  select(Cruise:days,  phyc.75, phyc.100, phyc.300) %>% 
  pivot_longer(phyc.75:phyc.300, names_to = "depth_interval", names_prefix = "phyc.", values_to = "phyc") %>% 
  mutate(depth_interval = ifelse(depth_interval == 75, "0 - 75 m", depth_interval),
         depth_interval = ifelse(depth_interval == 100, "75 - 100 m", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "100 - 300 m", depth_interval))


pivot_npp_data <- data %>% 
  select(Cruise:days, contains("npp")) %>% 
  pivot_longer(npp.75:npp.300, names_to = "depth_interval", names_prefix = "npp.", values_to = "npp") %>% 
  mutate(depth_interval = ifelse(depth_interval == 75, "0 - 75 m", depth_interval),
         depth_interval = ifelse(depth_interval == 100, "75 - 100 m", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "100 - 300 m", depth_interval))


pivot_bc_data <- data %>% 
  select(Cruise:days, contains("bc.")) %>% 
  pivot_longer(bc.75:bc.300, names_to = "depth_interval", names_prefix = "bc.", values_to = "bc") %>% 
  mutate(depth_interval = ifelse(depth_interval == 75, "0 - 75 m", depth_interval),
         depth_interval = ifelse(depth_interval == 100, "75 - 100 m", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "100 - 300 m", depth_interval))


pivot_bcd_data <- data %>% 
  select(Cruise:days, bcd.75, bcd.100, bcd.300) %>% 
  pivot_longer(bcd.75:bcd.300, names_to = "depth_interval", names_prefix = "bcd.", values_to = "bcd") %>% 
  mutate(depth_interval = ifelse(depth_interval == 75, "0 - 75 m", depth_interval),
         depth_interval = ifelse(depth_interval == 100, "75 - 100 m", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "100 - 300 m", depth_interval))


pivot_bc_phyc_data <- data %>% 
  select(Cruise:days, contains("bc_phyc")) %>% 
  pivot_longer(bc_phyc.75:bc_phyc.300, names_to = "depth_interval", names_prefix = "bc_phyc.", values_to = "bc.phyc") %>% 
  mutate(depth_interval = ifelse(depth_interval == 75, "0 - 75 m", depth_interval),
         depth_interval = ifelse(depth_interval == 100, "75 - 100 m", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "100 - 300 m", depth_interval))

pivot_doc_data <- data %>% 
  select(Cruise:days, contains("doc")) %>% 
  pivot_longer(doc.75:doc.300, names_to = "depth_interval", names_prefix = "doc.", values_to = "doc") %>% 
  mutate(depth_interval = ifelse(depth_interval == 75, "0 - 75 m", depth_interval),
         depth_interval = ifelse(depth_interval == 100, "75 - 100 m", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "100 - 300 m", depth_interval))

pivot_tdaa_data <- data %>% 
  select(Cruise:days, contains("tdaa")) %>% 
  pivot_longer(tdaa.75:tdaa.300, names_to = "depth_interval", names_prefix = "tdaa.", values_to = "tdaa") %>% 
  mutate(depth_interval = ifelse(depth_interval == 75, "0 - 75 m", depth_interval),
         depth_interval = ifelse(depth_interval == 100, "75 - 100 m", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "100 - 300 m", depth_interval))

pivoted <- left_join(pivot_phyc_data, pivot_npp_data) %>% 
  left_join(., pivot_bc_data) %>% 
  left_join(., pivot_bcd_data) %>% 
  left_join(., pivot_bc_phyc_data) %>% 
  left_join(., pivot_doc_data) %>% 
  left_join(., pivot_tdaa_data) 

```

# Plot Data

### Phyto Carbon

```{r phyC plot, echo = FALSE, warning = FALSE, message = FALSE}
phyc.plot <-  pivoted %>% 
  drop_na(phyc) %>% 
  ggplot(aes(x = days, y = phyc)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(linetype = eddy, color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(shape = eddy, fill = factor(depth_interval, levels = levels)), size = 6, color = "black", stroke = 1) + 
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("Phytoplankton Carbon, mmol m"^"-3"))), colour = "") +
  expand_limits(y = c(0.5,3)) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_manual(values = custom.colors) +
  scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  custom_theme() 
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```


### Bact Carbon

```{r bactC plot, echo = FALSE, warning = FALSE, message = FALSE}
bc.plot <-  pivoted %>% 
  drop_na(bc) %>% 
  ggplot(aes(x = days, y = bc)) +
   geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_line(aes(linetype = eddy, color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(shape = eddy, fill = factor(depth_interval, levels = levels)), size = 6, color = "black", stroke = 1) +  
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("Bacterioplankton Carbon, mmol m"^"-3"))), colour = "") +
  expand_limits(y = c(0.5,3)) +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_manual(values = custom.colors) +
  scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  custom_theme() 
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```


### BCD

```{r bcd plot, echo = FALSE, warning = FALSE, message = FALSE}
bcd.plot <-  pivoted %>% 
  drop_na(bcd) %>% 
  ggplot(aes(x = days, y = bcd)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(linetype = eddy, color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(shape = eddy, fill = factor(depth_interval, levels = levels)), size = 6, color = "black", stroke = 1) +  
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("BCD, mmol m"^"-3", "d"^-1))), colour = "") +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_manual(values = custom.colors) +
  scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  custom_theme() 
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```


### BC : PhyC

```{r bcd:phyc plot, echo = FALSE, warning = FALSE, message = FALSE}
bc_phyc.plot <-  pivoted %>% 
  drop_na(bc.phyc) %>% 
  ggplot(aes(x = days, y = bc.phyc)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(linetype = eddy, color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(shape = eddy, fill = factor(depth_interval, levels = levels)), size = 6, color = "black", stroke = 1) +  
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("Bacterioplankton: Phytoplankton Carbon"))), colour = "") +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_manual(values = custom.colors) +
  scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  custom_theme() 
 # facet_grid(rows = vars(depth_interval), scales = "free_y")
```

### DOC

```{r doc plot, echo = FALSE, warning = FALSE, message = FALSE}
doc.plot <-  pivoted %>% 
  drop_na(doc) %>% 
  ggplot(aes(x = days, y = doc)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_line(aes(linetype = eddy, color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(shape = eddy, fill = factor(depth_interval, levels = levels)), size = 6, color = "black", stroke = 1) +  
  labs(x = expression(italic(paste("Days on Station"))), y = expression(italic(paste("DOC, mmol m"^"-3"))), colour = "", fill = "Depth Interval", linetype = "Eddy Location", shape = "Eddy Location") +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_manual(values = custom.colors) +
  scale_color_manual(values = custom.colors) +
  guides(color = F, fill = guide_legend(override.aes = list(shape = 21))) +
  custom_theme() +
  theme( legend.key.size = unit(1, "cm"))
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```


### TDAA

```{r tdaa plot, echo = FALSE, warning = FALSE, message = FALSE}
tdaa.plot <-  pivoted %>% 
  drop_na(tdaa) %>% 
  ggplot(aes(x = days, y = tdaa)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_line(aes(linetype = eddy, color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(shape = eddy, fill = factor(depth_interval, levels = levels)), size = 6, color = "black", stroke = 1) +  
  labs(x = expression(italic(paste(""))), y = expression(italic(paste("TDAA, mmol m"^"-3"))), colour = "") +
  scale_shape_manual(values = c("Core" = 21, "Outside" = 24)) +
  scale_fill_manual(values = custom.colors) +
  scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  custom_theme() 
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```



```{r combine plots, echo = FALSE, warning = FALSE, message = FALSE, fig.height = 18, fig.width = 24}

patchwork <- (phyc.plot + bc.plot + bc_phyc.plot) / (bcd.plot + doc.plot + tdaa.plot)

patchwork +  
  plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(size = 22),
        plot.title = element_text(size = 36)) 

```














