---
title: "S4_Integration_Plots_Core"
author: "Nicholas Baetge"
date: "2/25/2021"
output: github_document
---

# Intro

Here, we plot the integrated from the multiday NAAMES station, N2S4.

```{r load packages, message = F, warning = F}
library(tidyverse)
library(lubridate)
library(patchwork)
library(ggpubr)
```

```{r aesthetics}
custom.colors <- c("AT39" = "#377EB8", "AT34" = "#4DAF4A", "AT38" = "#E41A1C", "AT32" = "#FF7F00", "Temperate" = "#A6CEE3", "Subpolar" = "#377EB8", "Subtropical" = "#FB9A99", "GS/Sargasso" = "#E41A1C", "Early Spring" = "#377EB8", "Late Spring" = "#4DAF4A","Early Autumn" = "#E41A1C", "Late Autumn" = "#FF7F00",  "0-75 m" = "#A50026", "75-200 m" = "#313695", "Euphotic" = "#A50026", "Upper Mesopelagic" = "#313695", "Mesopelagic" = "#d16cfa")

levels = c("GS/Sargasso", "Subtropical", "Temperate", "Subpolar",  "AT39-6", "AT34", "AT38", "AT32","South", "North", "Early Spring", "Late Spring","Early Autumn",  "Late Autumn", "0-75 m", "75-200 m", "200-300 m", "Euphotic", "Upper Mesopelagic", "Mesopelagic")

odv.colors <- c("#feb483", "#d31f2a", "#ffc000", "#27ab19", "#0db5e6", "#7139fe", "#d16cfa")
```


# Import Data

```{r import data, message=FALSE, warning=FALSE}
data <- read_rds("~/GITHUB/naames_multiday/Output/processed_data.rds") %>% 
  filter(Cruise == "AT34" & Station == 4) %>% 
  mutate(time = ymd_hms(datetime),
         interv = interval(first(time), time),
         dur = as.duration(interv),
         days = as.numeric(dur, "days"),
         eddy = ifelse(Date != "2016-05-27", "Core", "Periphery")) %>% 
  filter(eddy == "Core") %>% 
  select(Cruise, Station, Date, ez, sd_ez, eddy, time:days, bcd.ez:aou.300) %>% 
  distinct() %>% 
  mutate(ou.ez = (aou.ez - first(aou.ez)),
         ou.200 = (aou.200 - first(aou.200)),
         ou.300 = (aou.300 - first(aou.300))) %>% 
   mutate_at(vars(contains(c("tdaa", "bcd", "bp", "npp", "phyc"))), funs(. / 10^3)) #nM to mmol/m3 

```

# Pivot data

```{r pivot data, message=FALSE, warning=FALSE}
pivot_phyc_data <- data %>% 
  select(Cruise:days,  phyc.ez, phyc.200, phyc.300) %>% 
  pivot_longer(phyc.ez:phyc.300, names_to = "depth_interval", names_prefix = "phyc.", values_to = "phyc") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivot_chl_data <- data %>% 
  select(Cruise:days,  chl.ez, chl.200, chl.300) %>% 
  pivot_longer(chl.ez:chl.300, names_to = "depth_interval", names_prefix = "chl.", values_to = "chl") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivot_bc_data <- data %>% 
  select(Cruise:days,  bc.ez, bc.200, bc.300) %>% 
  pivot_longer(bc.ez:bc.300, names_to = "depth_interval", names_prefix = "bc.", values_to = "bc") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivot_phyto_data <- data %>% 
  select(Cruise:days,  phyto.ez, phyto.200, phyto.300) %>% 
  pivot_longer(phyto.ez:phyto.300, names_to = "depth_interval", names_prefix = "phyto.", values_to = "phyto") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))


pivot_ba_data <- data %>% 
  select(Cruise:days, contains("ba")) %>% 
  pivot_longer(ba.ez:ba.300, names_to = "depth_interval", names_prefix = "ba.", values_to = "ba") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivot_npp_data <- data %>% 
  select(Cruise:days, contains("npp")) %>% 
  pivot_longer(npp.ez:npp.300, names_to = "depth_interval", names_prefix = "npp.", values_to = "npp") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivot_bp_data <- data %>% 
  select(Cruise:days, bp.ez, bp.200, bp.300) %>% 
  pivot_longer(bp.ez:bp.300, names_to = "depth_interval", names_prefix = "bp.", values_to = "bp") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivot_bcd_data <- data %>% 
  select(Cruise:days, bcd.ez, bcd.200, bcd.300) %>% 
  pivot_longer(bcd.ez:bcd.300, names_to = "depth_interval", names_prefix = "bcd.", values_to = "bcd") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivot_doc_data <- data %>% 
  select(Cruise:days, contains("doc")) %>% 
  pivot_longer(doc.ez:doc.300, names_to = "depth_interval", names_prefix = "doc.", values_to = "doc") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivot_tdaa_data <- data %>% 
  select(Cruise:days, contains("tdaa")) %>% 
  pivot_longer(tdaa.ez:tdaa.300, names_to = "depth_interval", names_prefix = "tdaa.", values_to = "tdaa") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivot_aou_data <- data %>% 
  select(Cruise:days, contains("aou")) %>% 
  pivot_longer(aou.ez:aou.300, names_to = "depth_interval", names_prefix = "aou.", values_to = "aou") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivot_ou_data <- data %>% 
  select(Cruise:days, contains("ou")) %>% 
  select(-contains("aou")) %>% 
  pivot_longer(ou.ez:ou.300, names_to = "depth_interval", names_prefix = "ou.", values_to = "ou") %>% 
  mutate(depth_interval = ifelse(depth_interval == "ez", "Euphotic", depth_interval),
         depth_interval = ifelse(depth_interval == 200, "Upper Mesopelagic", depth_interval),
         depth_interval = ifelse(depth_interval == 300, "200-300 m", depth_interval))

pivoted <- left_join(pivot_phyc_data, pivot_npp_data) %>% 
  left_join(., pivot_phyto_data) %>% 
  left_join(., pivot_chl_data) %>% 
  left_join(., pivot_bc_data) %>% 
  left_join(., pivot_ba_data) %>% 
  left_join(., pivot_bp_data) %>% 
  left_join(., pivot_bcd_data) %>% 
  left_join(., pivot_doc_data) %>% 
  left_join(., pivot_tdaa_data) %>% 
  left_join(., pivot_aou_data) %>% 
  left_join(., pivot_ou_data) %>% 
  filter(depth_interval %in% c("Euphotic", "Upper Mesopelagic"))

```

# Plot Data

### Chl

```{r chl plot, echo = FALSE, warning = FALSE, message = FALSE}
chl.plot <-  pivoted %>% 
  drop_na(chl) %>% 
  ggplot(aes(x = days, y = chl)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "", y = expression(paste("Chl ", italic("a")," mg m"^"-3")), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```

### PhyC

```{r phyc plot, echo = FALSE, warning = FALSE, message = FALSE}
phyc.plot <-  pivoted %>% 
  drop_na(phyc) %>% 
  ggplot(aes(x = days, y = phyc)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "", y = expression(paste("Phytoplankton Carbon, mmol m"^"-3")), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```

### BC

```{r bc plot, echo = FALSE, warning = FALSE, message = FALSE}
bc.plot <-  pivoted %>% 
  drop_na(bc) %>% 
  ggplot(aes(x = days, y = bc)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "", y = expression(paste("Bacterioplankton Carbon, mmol m"^"-3")), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```


### Phyto

```{r phyto plot, echo = FALSE, warning = FALSE, message = FALSE}
phyto.plot <-  pivoted %>% 
  drop_na(phyto) %>% 
  ggplot(aes(x = days, y = phyto)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "", y = expression(paste("Phytoplankton Cells, m"^"-3")), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```

### BA

```{r ba plot, echo = FALSE, warning = FALSE, message = FALSE}
ba.plot <-  pivoted %>% 
  drop_na(ba) %>% 
  ggplot(aes(x = days, y = ba)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "", y = expression(paste("Bacterioplankton Cells, m"^"-3")), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```

### NPP

```{r npp plot, echo = FALSE, warning = FALSE, message = FALSE}
npp.plot <-  pivoted %>% 
  drop_na(npp) %>% 
  ggplot(aes(x = days, y = npp)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "", y = expression(paste("NPP, mmol m"^"-3", "d"^-1)), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```

### BP

```{r bp plot, echo = FALSE, warning = FALSE, message = FALSE}
bp.plot <-  pivoted %>% 
  drop_na(bp) %>% 
  ggplot(aes(x = days, y = bp)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "", y = expression(paste("BP, mmol m"^"-3", "d"^-1)), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```


### BCD

```{r bcd plot, echo = FALSE, warning = FALSE, message = FALSE}
bcd.plot <-  pivoted %>% 
  drop_na(bcd) %>% 
  ggplot(aes(x = days, y = bcd)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
   geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "", y = expression(paste("BCD, mmol m"^"-3", "d"^-1)), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```

### DOC

```{r doc plot, echo = FALSE, warning = FALSE, message = FALSE}
doc.plot <-  pivoted %>% 
  drop_na(doc) %>% 
  ggplot(aes(x = days, y = doc)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "Days on Station", y = expression(paste("DOC, mmol m"^"-3")), colour = "", fill = "Depth Horizon") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(linetype = F, color = F, fill = guide_legend(override.aes = list(shape = 21))) +
  theme_classic2(base_size = 16) +
  theme( legend.key.size = unit(1, "cm"))
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```


### TDAA

```{r tdaa plot, echo = FALSE, warning = FALSE, message = FALSE}
tdaa.plot <-  pivoted %>% 
  drop_na(tdaa) %>% 
  ggplot(aes(x = days, y = tdaa)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "Days on Station", y = expression(paste("TDAA, mmol m"^"-3")), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```

### AOU

```{r aou plot, echo = FALSE, warning = FALSE, message = FALSE}
aou.plot <-  pivoted %>% 
  drop_na(aou) %>% 
  ggplot(aes(x = days, y = aou)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "Days on Station", y = expression(paste("AOU, mmol m"^"-3")), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```


```{r our plot, echo = FALSE, warning = FALSE, message = FALSE}
ou.plot <-  pivoted %>% 
  drop_na(aou) %>% 
  ggplot(aes(x = days, y = ou)) +
  geom_rect( aes(xmin = 0.5, xmax = 1, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 1.5, xmax = 2, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_rect( aes(xmin = 2.5, xmax = 3, ymin = -Inf, ymax = Inf),
            fill = "light grey", alpha = 0.1) +
  geom_line(aes(color = factor(depth_interval, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(depth_interval, levels = levels)), shape = 21, size = 6, color = "black", stroke = 1, alpha = 0.7) +  
  labs(x = "Days on Station", y = expression(paste("∆AOU, mmol m"^-3)), colour = "") +
    scale_fill_manual(values = custom.colors) +
    scale_color_manual(values = custom.colors) +
  guides(color = F, fill = F, shape = F, linetype = F) +
  theme_classic2(base_size = 16)
 # facet_grid(rows = vars(depth_interval), scales = "free_y")

```



```{r combine plots, echo=FALSE, fig.height=14, fig.width=18, message=FALSE, warning=FALSE}

patchwork <- chl.plot + phyto.plot + ba.plot + phyc.plot + bc.plot +  npp.plot + bp.plot + bcd.plot + doc.plot + tdaa.plot + aou.plot + ou.plot

patchwork +  
  plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(size = 22),
        plot.title = element_text(size = 36)) 

```














